site_name: "QuakeFlow"
site_description: 'QuakeFlow: a Scalable Deep-learning-based Earthquake Monitoring Workflow with Cloud Computing'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'AI4EPS/QuakeFlow'
repo_url: 'https://github.com/ai4eps/QuakeFlow'
nav:
    - Overview: README.md
    - Pipeline: kubeflow/workflow.ipynb
    - Standard Formats: data_format.md
    # - Visualization: plot_catalog.ipynb
    # - FastAPI: fastapi.ipynb
    # - Deploy on cluster: k8s_readme.md
    # - Deploy on cloud: gcp_readme.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - exclude:
      glob:
        - PhaseNet/*
        - GaMMA/*
        - "*_demo"
extra:
  analytics:
    provider: google
    property: G-69DX3B35RK
