site_name: "QuakeFlow"
site_description: 'QuakeFlow: a Scalable Deep-learning-based Earthquake Monitoring Workflow with Cloud Computing'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'wayneweiqiang/QuakeFlow'
repo_url: 'https://github.com/wayneweiqiang/QuakeFlow'
nav:
    - Overview: README.md
    - Pipeline: workflow.ipynb
    - Visualization: plot_catalog.ipynb
    # - FastAPI: fastapi.ipynb
    # - Deploy on cluster: k8s_readme.md
    # - Deploy on cloud: gcp_readme.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter
  - exclude:
      glob:
        - PhaseNet/*
        - GMMA/*
        - "*_demo"