apiVersion: v1
kind: Pod
metadata:
  name: dataaccess52
spec:
  containers:
  - name: alpine
    image: zhuwq0/waveform-env:1.1
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: mypvc
      mountPath: /data
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: quakeflow-w8gfg-data-volume-52
