name: documentation

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
#     runs-on: macos-latest
#     runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.8
#           cache: 'pip'
#       - run: pip install -r requirements.txt
# #       - run: pip install mkdocs mkdocs-material mkdocs-jupyter mkdocs-exclude
#       - run: mkdocs gh-deploy --force

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - run: conda install mkdocs=1.3.0 mkdocs-material=8.4.1 mkdocs-material-extensions==1.0.3 mkdocs-jupyter=0.21.0 mkdocs-exclude -c conda-forge
      - run: $CONDA/bin/mkdocs gh-deploy --force
