name: documentation

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: sudo apt-get install -y mkdocs
      - run: pip install mkdocs-material mkdocs-jupyter mkdocs-exclude
      - run: mkdocs gh-deploy --force
