name: documentation

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
#     runs-on: ubuntu-latest
    runs-on: macos-latest
#     runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.4.2
      - run: pip install mkdocs-material==9.0.5
      - run: pip install mkdocs-jupyter==0.22.0
      - run: pip install mkdocs-exclude==1.0.2
      - run: mkdocs gh-deploy --force

#       - uses: conda-incubator/setup-miniconda@v2
#         with:
#           miniconda-version: "latest"
# #       - run: conda install mkdocs mkdocs-material mkdocs-jupyter mkdocs-exclude -c conda-forge
#       - run: $CONDA/bin/pip install mkdocs-material
#       - run: $CONDA/bin/pip install mkdocs mkdocs-material=="9.*" mkdocs-jupyter mkdocs-exclude
#       - run: $CONDA/bin/mkdocs gh-deploy --force
